# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing Access Group (EPG) '{{ epg.name }}'"
  cisco.aci.aci_epg:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    ap: "{{ ap.name }}"
    epg: "{{ epg.name }}"
    description: "{{ epg.description | default() }}"
    bd: "{{ epg.bridgedomain }}"
    # monitoring_policy: default
    # preferred_group: yes
    state: "{{ epg.state }}"
  delegate_to: localhost
- name: Process Access Group Domains
  ansible.builtin.include_tasks: domains/domain.yml
  when: epg.state == "present" and epg.domains is defined
  loop: "{{ epg.domains }}"
  loop_control:
    loop_var: domain
- name: Process Access Group Ports
  when: epg.state == "present" and epg.ports is defined
  ansible.builtin.include_tasks: ports/port.yml
  loop: "{{ epg.ports }}"
  loop_control:
    loop_var: port
- name: Process Access Group Contracts
  ansible.builtin.import_tasks: contracts.yml
  when: epg.state == "present" and epg.contracts is defined
