# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing L3out Interface Profile '{{ interface_profile.name }}'"
  cisco.aci.aci_l3out_logical_interface_profile:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    l3out: "{{ l3out.name }}"
    node_profile: "{{ node_profile.name }}"
    interface_profile: "{{ interface_profile.name }}"
    # description: "{{ interface_profile.description }}"
    state: "{{ interface_profile.state }}"
  delegate_to: localhost
- name: Process Interfaces
  ansible.builtin.include_tasks: interfaces/interface.yml
  when: interface_profile.state == "present" and interface_profile.interfaces is defined
  loop: "{{ interface_profile.interfaces }}"
  loop_control:
    loop_var: interface
