# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing Subnet '{{ subnet.gatewayip }}/{{ subnet.masklength }}'"
  cisco.aci.aci_bd_subnet:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    bd: "{{ bd.name }}"
    gateway: "{{ subnet.gatewayip }}"
    mask: "{{ subnet.masklength }}"
    state: "{{ subnet.state }}"
    preferred: "{{ subnet.primary }}"
    scope: "{{ subnet.scope | default(['private']) }}" # "private", "public", "shared"
  delegate_to: localhost
