# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing External Access Group '{{ extepg.name }}' Network '{{ subnet.network }}'"
  cisco.aci.aci_l3out_extsubnet:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    l3out: "{{ l3out.name }}"
    extepg: "{{ extepg.name }}"
    description: "{{ subnet.description | default() }}"
    network: "{{ subnet.network }}"
    scope: "{{ subnet.scope | default([]) }}"
    # aggregate: "{{ subnet.aggregate | default(['export-rtctl']) }}"
    state: "{{ subnet.state }}"
  delegate_to: localhost
