# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing BGP Peer: {{ peer.address }}'"
  cisco.aci.aci_l3out_bgp_peer:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    l3out: "{{ l3out.name }}"
    node_profile: "{{ node_profile.name }}"
    interface_profile: "{{ interface_profile.name }}"
    pod_id: "{{ interface.pod | default(1) }}"
    node_id: "{{ interface.node_id }}" # 101, 201-202 for vPC
    path_ep: "{{ interface.path }}" # eth1/12, my_vpc_ipg
    peer_ip: "{{ peer.address }}"
    remote_asn: "{{ peer.asn }}"
    state: "{{ peer.state }}"
    # bgp_controls:
    #   - nh-self
    #   - send-com
    #   - send-ext-com
    # peer_controls:
    #   - bfd
    # route_control_profiles:
    #   - tenant: "ansible_tenant"
    #     profile: "anstest_import"
    #     direction: "import"
    #   - tenant: "ansible_tenant"
    #     profile: "anstest_export"
    #     direction: "export"
    #     l3out: "anstest_l3out"
    #     state: present
    # ttl: 4
    # weight: 50
    admin_state: "{{ peer.admin_state | default('enabled') }}"
  delegate_to: localhost
