- name: "Process Tenant '{{ tenant.name }}' VRFs"
  ansible.builtin.include_tasks: networking/vrfs/vrf.yml
  when: tenant.networking.vrfs is defined
  loop: "{{ tenant.networking.vrfs }}"
  loop_control:
    loop_var: vrf
- name: "Process Tenant '{{ tenant.name }}' Bridge Domains"
  ansible.builtin.include_tasks: networking/bridgedomains/bridgedomain.yml
  when: tenant.networking.bridgedomains is defined
  loop: "{{ tenant.networking.bridgedomains }}"
  loop_control:
    loop_var: bd
