# - name: Set APIC Credential Information
#   tags: always
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing Tenant '{{ tenant.name }}'"
  tags: always
  cisco.aci.aci_tenant:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"    
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    description: "{{ tenant.description }}"
    state: "{{ tenant.state }}"
  delegate_to: localhost
- name: Process Tenant Networking
  ansible.builtin.import_tasks: networking.yml
  when: tenant.state == "present" and tenant.networking is defined
  tags: networking
- name: Process Tenant Security
  tags: security
  ansible.builtin.import_tasks: security.yml
  when: tenant.state == "present" and tenant.security is defined
- name: Process Tenant Applications
  tags: applications
  ansible.builtin.import_tasks: applications.yml
  when: tenant.state == "present" and tenant.applications is defined
