# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing L3out Node Profile '{{ node_profile.name }}'"
  cisco.aci.aci_l3out_logical_node_profile:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"  
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    node_profile: "{{ node_profile.name }}"
    description: "{{ node_profile.description }}"
    l3out: "{{ l3out.name }}"
    state: "{{ node_profile.state }}"
  delegate_to: localhost
- name: Process Nodes
  ansible.builtin.include_tasks: nodes/node.yml
  when: node_profile.state == "present" and node_profile.nodes is defined
  loop: "{{ node_profile.nodes }}"
  loop_control:
    loop_var: node
- name: Process Interface Profiles
  ansible.builtin.include_tasks: interfaceprofiles/interfaceprofile.yml
  when: node_profile.state == "present" and node_profile.interface_profiles is defined
  loop: "{{ node_profile.interface_profiles }}"
  loop_control:
    loop_var: interface_profile
