# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing Access Port 'Pod:{{ port.pod }} Node(s):{{ port.leafs }} Interface:{{ port.interface }} VLAN:{{ port.vlan }}'"
  cisco.aci.aci_static_binding_to_epg:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    ap: "{{ ap.name }}"
    epg: "{{ epg.name }}"
    encap_id: "{{ port.vlan }}"
    # deploy_immediacy: lazy
    interface_mode: "{{ port.mode }}" # 802.1p, access, native, regular, trunk, untagged
    interface_type: "{{ port.type }}" # fex, port_channel, vpc, fex_port_channel, fex_vpc
    pod_id: "{{ port.pod | default(1) }}"
    leafs: "{{ port.switches }}"
    interface: "{{ port.interface }}"
    state: "{{ port.state }}"
  delegate_to: localhost
