# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing Application Profile '{{ ap.name }}'"
  cisco.aci.aci_ap:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    ap: "{{ ap.name }}"
    description: "{{ ap.description | default() }}"
    # monitoring_policy: default
    state: "{{ ap.state }}"
  delegate_to: localhost
- name: Process Access Groups (EPGs)
  ansible.builtin.include_tasks: epgs/epg.yml
  when: ap.state == "present" and ap.accessgroups is defined
  loop: "{{ ap.accessgroups }}"
  loop_control:
    loop_var: epg
