# - name: Set APIC Credential Information
#   ansible.builtin.set_fact:
#     aci_info: &aci_info
#       host: "{{ apic_hostname }}"
#       username: "{{ apic_username }}"
#       password: "{{ apic_password }}"
#       validate_certs: false
#       output_level: debug
#       timeout: 120
#       annotation: orchestrator:ansible
#       output_path: "{{ output_path }}"
- name: "Processing L3out Node '{{ node.id }}'"
  cisco.aci.aci_l3out_logical_node:
    ### APIC Details ###
    # <<: *aci_info
    host: "{{ ansibile_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"  
    validate_certs: "{{ validate_certs }}"
    output_level: "{{ output_level }}"
    timeout: "{{ timeout }}"
    annotation: orchestrator:ansible
    output_path: "{{ output_path }}"
    ### Module Details ###
    tenant: "{{ tenant.name }}"
    l3out: "{{ l3out.name }}"
    node_profile: "{{ node_profile.name }}"
    pod_id: "{{ node.pod | default(1) }}"
    node_id: "{{ node.id }}"
    router_id: "{{ node.router_id | default() }}"
    state: "{{ node.state }}"
  delegate_to: localhost
